name: dot_matrix
description: 3D Material Layering System for Robotic Manufacturing - Motorcycle Jacket Protection.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  three_dart: ^0.0.16
  three_dart_jsm: ^0.0.10
  urdf_parser: ^0.0.5
  vector_math: ^2.1.0
  file_picker: ^8.1.4
  path_provider: ^2.0.0
  path: ^1.8.0
  csv: ^5.0.0
  intl: ^0.19.0
  flutter_gl: ^0.0.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/icons/